steps:
  - name: maven:3.6.3-jdk-11-slim
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile', '-t', 'gcr.io/$PROJECT_ID/bff-test', '.']
    images: ['gcr.io/$PROJECT_ID/bff-test']